#!/usr/bin/env python3
# This file was generated by WRAP
from os import getenv, environ, listdir, system
from os.path import splitext
from pathlib import Path
from sys import argv

from base_processors.generic_argparse_processor import call


class wrap:
    @staticmethod
    def gen(
            input_path: str = getenv("WRAP_INPUT_PATH", ""),
            output_path: str = getenv("WRAP_OUTPUT_PATH", ""),
            processor_path: str = getenv("WRAP_PROCESSOR_PATH", ""),
            clean_output_path: bool = getenv("WRAP_CLEAN_OUTPUT_BEFORE_GEN", "false").lower() == "true",
            debug_mode: bool = getenv("WRAP_DEBUG_MODE", "false").lower() == "true",
    ):
        flat_file_list = [Path(f"{path}/{file}") for path in input_path.split(":") for file in listdir(path)]
        flat_loader_list = [Path(f"{path}/{file}") for path in processor_path.split(":") for file in listdir(path)]
        print(flat_file_list) if debug_mode else None
        print(flat_loader_list) if debug_mode else None
        # map the loaders to the files based on the file name
        loader_map = {
            file: loader for file in flat_file_list
            for loader in flat_loader_list if
            loader.name != "__pycache__" and file.name.endswith(splitext(loader.name)[1])
        }
        print(loader_map) if debug_mode else None
        # clean output path
        if clean_output_path:
            print("Cleaning old files") if debug_mode else None
            system(f"rm {output_path}/*")

        # run the loaders on the files
        for file, loader in loader_map.items():
            print(f"Running {loader} on {file}") if debug_mode else None
            system(f"chmod +x {loader}")
            system(f"{loader} {file} {output_path} {'--debug_mode' if debug_mode else ''}")

call(wrap)
